### ISSUE TITLE
Fonts do not load anymore when Meteor runs in subfolder

### ISSUE THREAD

**Issue by javdl** [Zodiase/meteor-mdl#24] opened 2015-12-04 18:58 UTC
Since updating Meteor to 1.2 + latest package fonts are not loaded when running Meteor in a subfolder. Our apps run with:
ROOT_URL=https://example.com/some-subfolder-name

Previously this worked fine with this package, now it is broken cause it tries to load the fonts from example.com/packages/zodiase_mdl/fonts/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2
while it should be
example.com/some-subfolder-name/packages/zodiase_mdl/fonts/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2

**Comment by Zodiase** [comment] 2015-12-04 20:00
For the moment you could add this to the `<head>` to load the font from Google directly.

``` HTML
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

I've never put my apps under any subfolder so this issue never came up to me. I don't have a setup here with a meteor app running in a subfolder. Do you have some quick instructions for setting things up to reproduce the situation you are having so I could check if my fixes will work for you?

**Comment by Zodiase** [comment] 2015-12-04 20:07
I guess one easy fix would be reverting to the old time when I just embedded the font files in the css file. That way I don't need to deal with this path issue. But that way we sacrifice some bandwidth as the browser would download all the font data even only one of them is needed.

**Comment by Zodiase** [comment] 2015-12-04 20:36
I just published a new version `1.0.6_2` with a fix I think works. Let me know if it's not working.

**Comment by javdl** [comment] 2016-01-06 11:12
Thanks a lot, your fix is working just fine! Tested on Multiple Meteor apps & multiple domain/subfolder combinations.

**Comment by javdl** [comment] 2016-02-12 10:41
Facing this issue again since 1.1.1

**Comment by Zodiase** [comment] 2016-02-12 18:07
That's odd... The last fix was changing absolute path to relative path (`/packages/zodiase_mdl/fonts/` to `fonts/`). In 1.1.1, even though the fonts are separated into a dedicated package, relative paths are still used. E.g. `packages/zodiase_material-design-icons-fonts/iconfont/MaterialIcons-Regular.eot`.

Could you verify the font urls in the `merged-stylesheets.css` in your apps?

**Comment by Zodiase** [comment] 2016-02-12 18:42
I tried running `ROOT_URL=localhost:4000/foo/ meteor -p 4000` and the fonts loaded fine at `http://localhost:4000/foo`

**Comment by Zodiase** [comment] 2016-09-16 21:47
Closing due to inactivity.

**Closed as completed by Zodiase** 2016-09-16 21:47 UTC
Labels: bug
