### ISSUE TITLE
MDL Table not rendering correctly when new row added via template

### ISSUE THREAD

**Issue by boxtree** [Zodiase/meteor-mdl#38] opened 2016-05-01 12:22 UTC
Hi 

Great work on getting MDL into meteor!

I'm using the latest versions of meteor etc...

I have a simple blaze template that has a "add new item" button then a table that lists the items in the collection. The add button does a meteor.call() to add a document to the collection. Then reactivity causes the table below to re-render.

```
    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Name</th>
          <th>Status</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
      {{#each issues _id}}
        <tr>
          <td class="mdl-data-table__cell--non-numeric">{{name}}</td>
          <td onClick="FlowRouter.go('/editIssue/{{_id}}')">{{status}}</td>
          <td>{{description}}</td>
        </tr>
      {{/each}}
      </tbody>
    </table>
```

The result immediately after adding a document looks like the attached. After a refresh it displays correctly.

![image](https://cloud.githubusercontent.com/assets/18900411/14941753/606397f4-0f9f-11e6-8bba-0d9c64bf9b74.png)

Thanks

**Comment by Zodiase** [comment] 2016-05-01 22:01
Duplicate of #10.

In short: don't ever use `mdl-data-table--selectable`, it's buggy and doesn't work at all with dynamic content.
Check out the demo app here: https://github.com/Zodiase/meteor-mdl/tree/master/integration-tests/issue10. It has a fairly simple implementation of `mdl-data-table--selectable` that works.

**Closed as completed by Zodiase** 2016-05-01 22:02 UTC
Labels: duplicate
