### ISSUE TITLE
MDL and Meteor 1.3

### ISSUE THREAD

**Issue by seifip** [Zodiase/meteor-mdl#32] opened 2016-03-03 06:01 UTC
MDL works great with Meteor 1.2, but I'm having troubles getting it to work with 1.3 beta 11.

Most of it works correctly, but the dropdown menus are broken and the Console reads `Uncaught ReferenceError: componentHandler is not defined` and `MDl disabled. Create a file named 'zodiase-mdl.json' at the root of the app to enable.`.

zodiase-mdl.json is definitely there (haven't changed anything before upgrade to 1.3) and it even appears like MDL _is_ using it - otherwise the colour definition would be loaded.

Is 1.1.1 compatible with Meteor 1.3?

**Comment by Zodiase** [comment] 2016-03-03 17:07
I haven't started working on supporting Meteor 1.3. From your description it looks like the plugin system is changed quite a bit in 1.3. I'll take a look at it soon.

**Comment by seifip** [comment] 2016-03-03 17:09
Thanks! 1.3 seems to be nearing release, so it's a good time to start thinking about it :)

**Comment by Zodiase** [comment] 2016-03-04 09:03
Short version of the story:
I created an empty app and updated it to `Meteor 1.3-beta.12` and then added `zodiase:mdl@1.1.1_1` and got no error so far.

There isn't a longer version of the story... But I did published a new version (`1.1.1` revision 1) and I'm not sure if that has any impact on the errors you are seeing.

**Comment by Zodiase** [comment] 2016-03-04 09:05
If you are still seeing the errors, could you provide a minimum case to reproduce the errors?

**Comment by seifip** [comment] 2016-03-05 11:46
ok, so to test that it's not just my project, I pulled the example todo-list app, installed zodiase:mdl 1.1.2, added the .json file, upgraded to meteor 1.3-beta.12 and I still get the same errors:

![image](https://cloud.githubusercontent.com/assets/636168/13547365/5ab987b8-e313-11e5-9546-7928ced53b06.png)

yet here again, the .json is actually loaded correctly:

![image](https://cloud.githubusercontent.com/assets/636168/13547373/97d4c86a-e313-11e5-8e0f-56ac01d1a00f.png)

**Comment by Zodiase** [comment] 2016-03-05 13:03
I found the cause of this issue. For some reason the new `isobuild:compiler-plugin` is only allowing me to add only one js file. If I do:

``` JavaScript
inputFile.addJavaScript(js1);
inputFile.addJavaScript(js2);
inputFile.addJavaScript(js3);
```

then only `js3` will show up in the final js file sent to the client. This looks to me is definitely a bug in the Meteor 1.3 beta.

**Comment by Zodiase** [comment] 2016-03-05 13:05
This package relies on this api to add js files on demand. Apparently this bug caused all js files but the last one to be missing, and hence the error you are getting.

**Comment by seifip** [comment] 2016-03-05 15:03
I believe they are discussing the problem at https://github.com/meteor/meteor/issues/6014 but they say it's fixed in beta 11?

**Comment by Zodiase** [comment] 2016-03-06 01:12
That was a whole different issue; at that time `addJavaScript` was not working at all. This time, it only adds the last file no matter how many times I call it.

**Comment by Zodiase** [comment] 2016-03-06 01:14
They've worked `compiler-plugin` a lot and I haven't got enough time to understand how it's working now and what part of the logic caused this problem.

**Comment by Zodiase** [comment] 2016-03-06 02:05
Looks like they confirmed the bug. (meteor/meteor/issues/6422)

Well, from the look of how many issues there still are for `beta.12` I'm guessing they'd need another new beta release or two and perhaps 4 months to get to a stable state to release Meteor 1.3.

**Comment by ramijarrar** [comment] 2016-03-23 20:25
@Zodiase 4 months? :laughing:

**Comment by Zodiase** [comment] 2016-03-23 20:45
@ramijarrar I have no idea why they are rushing 1.3 out with so many known issues pushed to 1.3.1. Marketing I guess.

**Comment by ramijarrar** [comment] 2016-03-29 06:55
Trying with the official 1.3 release at the moment and there doesn't appear to be any incompatibility issues. 

@Zodiase Would it be possible to move options into "package.json"?

**Comment by Zodiase** [comment] 2016-04-01 17:38
@ramijarrar That's good to know.

About moving the options into `package.json`, from what I can see the benefit is having one fewer file in the app root directory. The problems it creates, however, include:
1. Difficulty in picking a namespace in the `package.json` to ensure a conflict with other packages, Meteor itself or the user code would **never** happen. Or at least when it has to happen, the user will always have a way to work around it. Currently with `zodiase-mdl.json`, it's always possible to just not use that file path and everything is perfect. With `package.json` though, it's unpredictable; too many packages (now including npm stuff) could be fiddling with it.
2. Making it BC. How to handle scenarios like when both `zodiase-mdl.json` and `package.json` are present? It might not be too difficult to come up with a workable strategy but the planning takes time and some user feedback.

Please let me know if there's any benefit of doing so that I'm not aware of. But to me it's just too much trouble to be worth it.

On the other hand, I'd like to see how other packages are going to take advantage of `package.json` and get a sense of what other package authors would do and see if there's going to be a convention I could safely follow.

But I might be just living under a giant rock and there's already lots of packages doing what you proposed. In that case please do point me to some resources and I'd love to learn from them.

**Comment by ramijarrar** [comment] 2016-04-02 00:32
Here is an example: https://github.com/juliancwirko/meteor-postcss
1. If you take a closer look at the source, they are just parsing the `packages.json` file and reading the relevant key. So something like `zodiase-mdl` for this package should prevent any conflicts with namespace/unpredictability.
2. As far as backwards compatibility is concerned, I'm not sure why we could not just continue 
   loading the settings file as usual and then implement this as a layer on top of that. The interface does not need to change either, just mirror what we have now under `packages.json`.

I don't think there is much more to be gained here other than reducing clutter as you mentioned, so definitely no hurry/urgency with this. Just something to consider as a positive addition to the current UX.

**Comment by Zodiase** [comment] 2016-04-12 21:35
@ramijarrar The problem with having both `zodiase-mdl.json` and `packages.json` is the limitation from the `MultiFileCachingCompiler` that this package relies on.

The `MultiFileCachingCompiler` would gather a list of files meeting my set filter (exact match of `'zodiase-mdl.json'` in this case) and run `compileOneFile` that I defined on each of the files.

Generally I have no control over the overall process; I could only decide what to do for each matched file.

Now if I set the filter to match both `zodiase-mdl.json` and `packages.json`, then my "compiler" would run twice, adding two set of files, with potentially different settings, to the app.

Also the way `MultiFileCachingCompiler` is written makes it really hard to do something like: OK I'm looking at file A, let me check if file B is also present to see what I should do with file A.

Also, if I remember correctly, two compilers can't register for the same extension or the build will fail to an exception. I haven't tested to find out how that rule applies to exact filename matches.

**Comment by Zodiase** [comment] 2016-04-12 21:54
@ramijarrar That `postcss` is interesting... I was doing almost the same thing many releases ago, using `process.cwd()` and `fs` to read the settings file, except I did it in `package.js` instead of a file added by `package.js`. And that didn't work out as expected (see #26). It's good to know that `postcss` works for people and that just gave me an idea on another topic...

**Comment by jhuenges** [comment] 2016-06-06 21:43
Any update on 1.3 support?

**Comment by Zodiase** [comment] 2016-06-07 00:45
@jhuenges Are you having trouble using the package with Meteor 1.3? It should work.

**Comment by jhuenges** [comment] 2016-06-07 07:18
No, sorry! I haven't actually tested it yet. Was just asking because the issue is open

**Comment by Zodiase** [comment] 2016-06-07 16:03
@jhuenges There had been a few things in earlier releases of Meteor 1.3 breaking this package but they seem to be gone after some point in time. Really hard to tell what happened since Meteor's release version doesn't lock down its core packages. But at least now everything is fine so far :D.

This issue was left open since I wasn't sure if some updates in Meteor 1.3 core packages would break this package again... But now I think I'll just let new issues be new issues. Closing now.

**Closed as completed by Zodiase** 2016-06-07 16:03 UTC
