### ISSUE TITLE
Form submit event doesn't fire

### ISSUE THREAD

**Issue by vnmone** [Zodiase/meteor-mdl#25] opened 2015-12-18 15:19 UTC
Here is meteorPad example:
http://meteorpad.com/pad/zjtAP3zeFQBAth2ax/Copy%20of%20material-design-lite-test

submit event doesn't fire.

without mdl pack works properly

**Comment by Zodiase** [comment] 2015-12-19 00:59
Duplicate of #2.

**Comment by Zodiase** [comment] 2015-12-19 01:03
In short, blaze (Template) events are registered on the root element(s) of individual templates. However, MDL components sometimes shift elements around. In this case, for example, the layout component would create a wrapper container element and move itself inside that container. During this process, all the event listeners associated with the root element (the mdl-layout element) get destroyed.

**Closed as completed by Zodiase** 2015-12-19 01:03 UTC
Labels: duplicate

**Comment by vnmone** [comment] 2015-12-21 09:42
Sorry for my blindness.
